[package]
name = "yarve"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "1.1.1"
num-traits = "0.2"
num-derive = "0.3"
rangemap = "0.1.11"
